name: Weekly Mission
description: 주차별 미션 과제를 위한 이슈
title: 'W{주차} 미션 – {닉네임/이름}' # 생성 시 직접 입력
labels: ['weekly']
body:
    - type: dropdown
      id: week
      attributes:
          label: 주차
          options:
              [
                  '0',
                  '1',
                  '2',
                  '3',
                  '4',
                  '5',
                  '6',
                  '7',
                  '8',
                  '9',
                  '10',
                  '11',
                  '12',
              ]
      validations:
          required: true

    - type: input
      id: member
      attributes:
          label: 닉네임/이름
          placeholder: '예: 코튼/김연진'
      validations:
          required: true

    - type: checkboxes
      id: tasks
      attributes:
          label: 이번 주 완료 조건
          options:
              - label: 미션 완료
              - label: 폴더 구조 정리
              - label: PR 생성 및 리뷰 반영

    - type: markdown
      attributes:
          value: |
              > 📌 **이슈 생성 후 해야 할 일**
              > 1) 라벨 `week:{주차}` 직접 추가 (예: `week:3`)  
              > 2) 마일스톤 `Week {주차}` 직접 지정 (예: `Week 3`)
              > 3) PR 본문에 `Closes #이슈번호` 포함
