name: Auto-Assign Week Label & Milestone
on:
    issues:
        types: [opened, edited, reopened]

jobs:
    assign:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v7
              with:
                  script: |
                      const owner = context.repo.owner;
                      const repo = context.repo.repo;
                      const issue = context.payload.issue;

                      try {
                        // 제목 맨 앞의 W0~W12 매칭
                        const m = issue.title.match(/^W(\d{1,2})\b/i);
                        if (!m) {
                          core.info("No week prefix found (expected W0~W12). Skipping.");
                          return; // 스킵 = 성공처리
                        }

                        const weekNum = parseInt(m[1], 10);
                        if (Number.isNaN(weekNum) || weekNum < 0 || weekNum > 12) {
                          core.warning(`Week number out of range: ${weekNum}. Skipping.`);
                          return; // 스킵 = 성공처리
                        }

                        // 1) 라벨 week:N 부여
                        try {
                          const weekLabel = `week:${weekNum}`;
                          const existingLabels = (issue.labels || []).map(l => l.name);
                          if (!existingLabels.includes(weekLabel)) {
                            await github.rest.issues.addLabels({
                              owner, repo, issue_number: issue.number, labels: [weekLabel]
                            });
                            core.info(`Added label ${weekLabel}`);
                          } else {
                            core.info(`Label ${weekLabel} already present`);
                          }
                        } catch (e) {
                          core.warning(`라벨 추가 실패: ${e.message}`);
                        }

                        // 2) 마일스톤 "Week N" 할당 (있을 때만)
                        try {
                          const milestoneName = `Week ${weekNum}`;
                          const { data: milestones } = await github.rest.issues.listMilestones({
                            owner, repo, state: "open"
                          });
                          const found = milestones.find(m => m.title === milestoneName);
                          if (found && (!issue.milestone || issue.milestone.title !== milestoneName)) {
                            await github.rest.issues.update({
                              owner, repo, issue_number: issue.number, milestone: found.number
                            });
                            core.info(`Assigned milestone ${milestoneName}`);
                          } else if (!found) {
                            core.warning(`Milestone ${milestoneName} not found (run init-weeks workflow first).`);
                          } else {
                            core.info(`Milestone ${milestoneName} already assigned`);
                          }
                        } catch (e) {
                          core.warning(`마일스톤 할당 실패: ${e.message}`);
                        }
                      } catch (e) {
                        // 예기치 못한 오류도 실패로 만들지 않고 경고만 기록
                        core.warning(`Auto-assign script unexpected error: ${e.message}`);
                      }
