name: Init Week Labels & Milestones
on:
    workflow_dispatch:

jobs:
    init-weeks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v7
              with:
                  script: |
                      const owner = context.repo.owner;
                      const repo = context.repo.repo;

                      // 라벨: week:0 ~ week:12
                      for (let i = 0; i <= 12; i++) {
                        const name = `week:${i}`;
                        const color = "1D76DB";
                        try {
                          await github.rest.issues.createLabel({ owner, repo, name, color });
                          core.info(`Created label ${name}`);
                        } catch (e) {
                          core.info(`Label ${name} may already exist: ${e.message}`);
                        }
                      }

                      // 마일스톤: Week 0 ~ Week 12
                      for (let i = 0; i <= 12; i++) {
                        const title = `Week ${i}`;
                        try {
                          await github.rest.issues.createMilestone({ owner, repo, title });
                          core.info(`Created milestone ${title}`);
                        } catch (e) {
                          core.info(`Milestone ${title} may already exist: ${e.message}`);
                        }
                      }
