name: Rename Weekly Issue Title
on:
    issues:
        types: [opened, edited]

jobs:
    rename:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v7
              with:
                  script: |
                      const owner = context.repo.owner;
                      const repo = context.repo.repo;
                      const issue = context.payload.issue;

                      try {
                        // 이미 원하는 형태라면 패스
                        if (/^W\d{1,2}\s미션\s–\s.+$/.test(issue.title)) {
                          core.info("Title already normalized.");
                          return;
                        }

                        const body = issue.body || "";

                        // 주차 추출 (### 주차 바로 아래 숫자)
                        const weekMatch = body.match(/###\s*주차\s*\r?\n\s*([0-9]{1,2})\b/i);
                        // 닉네임/이름 추출 (### 닉네임/이름 바로 아래 줄)
                        const memberMatch = body.match(/###\s*닉네임\/이름\s*\r?\n\s*(.+)\s*$/im);

                        if (!weekMatch || !memberMatch) {
                          core.warning("주차 또는 닉네임/이름을 본문에서 찾을 수 없음. 제목 변경 스킵.");
                          return;
                        }

                        const week = parseInt(weekMatch[1], 10);
                        if (Number.isNaN(week) || week < 0 || week > 12) {
                          core.warning(`주차 값이 범위를 벗어남: ${week}. 스킵.`);
                          return;
                        }

                        const member = memberMatch[1].trim();
                        const newTitle = `W${week} 미션 – ${member}`;

                        if (issue.title === newTitle) {
                          core.info("제목이 이미 최신 상태.");
                          return;
                        }

                        try {
                          await github.rest.issues.update({
                            owner,
                            repo,
                            issue_number: issue.number,
                            title: newTitle,
                          });
                          core.info(`제목 변경 완료: ${newTitle}`);
                        } catch (e) {
                          core.warning(`제목 업데이트 실패: ${e.message}`);
                        }

                      } catch (e) {
                        core.warning(`Rename script unexpected error: ${e.message}`);
                      }
